/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package main.java;

public class Library {
	
	public Library() {}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
